---
- name: Permission present example
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure permission TestPerm1 is present
    freeipa.ansible_freeipa.ipapermission:
      name: TestPerm1
      rename: TestPermRenamed
      state: renamed
