
- name: Setup reverse proxy
  hosts: default
  remote_user: pi

  tasks:
    - name: Install prerequisites
      with_item:
        - libtiff5
        - ibopenjp2-7
        - python3
        - python3-pip
      package:
        state: present
        name: "{{ item }}"

    - name: Execute docker-compose
      environment: "{{ env_vars }}"
      community.general.docker_compose:
        project_src: .