version: "3.7"
services:
  organizr:
    image: organizrtools/organizr-v2
    container_name: organizr
    environment:
        - PUID
        - PGID
        - TZ
    volumes:
        - ${SERVICES_ROOT}/${ORGANIZR_ROOT:-organizr}/config:/config
        - ${SERVICES_ROOT}/${ORGANIZR_ROOT:-organizr}/db:/db
    restart: unless-stopped
