- import_playbook: ./ubuntu-20.04-template.yml

- name: Provision Ubuntu Template with Docker
  hosts: default
  collections:
      - professorsalty.homelab

  tasks:
    - include_role: 
        name: install_docker
      vars:
        loki_server_address: logger.land:3100
        template_username: toor
