- import_playbook: ./ubuntu-20.04-template.yml

- name: Setup an apt-cache proxy
  hosts: default
  become: true
  remote_user: toor

  tasks:
    - name: Install apt-cacher
      apt:
        name: apt_cacher
        state: present