- name: Setup automation
  hosts: default
  remote_user: toor
  collections:
      - professorsalty.homelab

  tasks:
    - name: Include common env vars
      include_vars: ../../default_env_vars.yml

    - name: Include encrypted Samba credentials
      include_vars: ../../../vaults/samba_users.vault

    - name: Allow ports 
      include_role:
        name: ufw_allow_ports
      vars:
        configs:
          - service: Node-Red
            port: 1880
          - service: Mosquitto
            port: 1883
          - service: HomeAssistant
            port: 8123

    - name: Execute docker-compose
      environment: "{{ env_vars }}"
      community.general.docker_compose:
        project_src: .

    - name: Run watchtower with proxy
      include_role:
        name: run_watchtower
