- import_playbook: ./ubuntu-20.04-template.yml

- name: Provision Ubuntu Template with Docker
  hosts: default
  remote_user: toor
  collections:
      - professorsalty.homelab

  tasks:
    - include_role: 
        name: docker
