- name: Setup office
  hosts: default
  remote_user: toor
  collections:
      - professorsalty.homelab

  tasks:
    - name: Include common env vars
      include_vars: ../../default_env_vars.yml

    - name: Include encrypted Samba credentials
      include_vars: ../../../vaults/samba_users.vault

    - name: Allow ports 
      include_role:
        name: ufw_allow_ports
      vars:
        configs:
          - service: Nextcloud
            port: 80
          - service: Filestash
            port: 8334
          - service: Papermerge
            port: 8000
          - service: CyberChef
            port: 8001
    
    - name: Run docker-compose file
      environment: "{{ env_vars }}"
      community.general.docker_compose:
        project_src: "."
        state: present

    - name: Run watchtower with proxy
      include_role:
        name: run_watchtower